<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46809" started-at="2022-09-26T15:34:13 IST" finished-at="2022-09-26T15:35:00 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46809" started-at="2022-09-26T15:34:13 IST" finished-at="2022-09-26T15:35:00 IST">
      <class name="org.pom_testCases.TestCases">
        <test-method status="PASS" signature="configReadercalling()[pri:0, instance:org.pom_testCases.TestCases@8e24743]" name="configReadercalling" is-config="true" duration-ms="23" started-at="2022-09-26T15:34:13 IST" finished-at="2022-09-26T15:34:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configReadercalling -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:org.pom_testCases.TestCases@8e24743]" name="launchBrowser" is-config="true" duration-ms="18986" started-at="2022-09-26T15:34:13 IST" finished-at="2022-09-26T15:34:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="VerifyDetails()[pri:1, instance:org.pom_testCases.TestCases@8e24743]" name="VerifyDetails" duration-ms="27391" started-at="2022-09-26T15:34:32 IST" finished-at="2022-09-26T15:34:59 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17 December 2021] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17 December 2021] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.pom_page.SearchPage_Wiki.applyAssertionOnReleaseDate(SearchPage_Wiki.java:69)
at org.pom_testCases.TestCases.VerifyDetails(TestCases.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyDetails -->
        <test-method status="PASS" signature="closeBrowser1()[pri:0, instance:org.pom_testCases.TestCases@8e24743]" name="closeBrowser1" is-config="true" duration-ms="332" started-at="2022-09-26T15:34:59 IST" finished-at="2022-09-26T15:35:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.pom_testCases.TestCases@8e24743]" name="tearDown" is-config="true" duration-ms="553" started-at="2022-09-26T15:35:00 IST" finished-at="2022-09-26T15:35:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.pom_testCases.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
